# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffc5a70a3254851c3b4e19aca95470d861d29641fb6bd3957685437078c8459198400c16ccc653449ba20612a8b2adc0f7480472dd395bb7c2804670f693260

test:
  secret_key_base: 0429a73826682726ffa9a37105a3e26eee8106b328ebc4060346bf3e0c812fbb38fb54641631c8ec8e5f725ac8c0ad8695a3c57efdb860defdc9c5ba25422d93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
